name : DSW test
on:
  push:
    branches:
      -main
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]  
  schedule:
    - cron: '11 11 * * 5'
    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:    
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Hello World"
          echo "The job was triggered by event ${{ github.event_name }}"
          echo "branch name is ${{ github.reg }}"
      - uses: actions/checkout@v3.3.0
      - run: tree -a
