name: staged deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == "workflow_dispatch"
    steps:
      - run: "Build something"
      
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == "workflow_dispatch"
    environment: test
    needs: build
    steps:
      - run: "Test something"
    
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == "workflow_dispatch"
    environment: load-test
    needs: build
    steps:
      - run: |
          echo "Load Test something"
          sleep 15
      
  Production:
    runs-on: ubuntu-latest
    if: github.event_name == "workflow_dispatch"
    environment:
      name: Production
      url: http://www.writeabout.it
    steps:
      - run: |
          echo "Step 1"
          sleep 15
      - run: |
          echo "Step 2"
          sleep 15
      
